INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (1, 'Cel i misja: Pomoc dzieciom z ubogich rodzin. ', true, 'Fundacja "Dbam o Zdrowie"');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (2, 'Cel i misja: Pomoc wybudzaniu dzieci ze śpiączki.', true, 'Fundacja "A kogo"');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (3, 'Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji życiowej.', true, 'Fundacja “Dla dzieci"');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (4, 'Cel i misja: Pomoc dla osób nie posiadających miejsca zamieszkania', true, 'Fundacja “Bez domu”');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (5, 'Cel i misja: Pomoc dzieciom z ubogich rodzin.', true, 'Fundacja "Dbam o Zdrowie"');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (6, 'Cel i misja: Pomoc wybudzaniu dzieci ze śpiączki. Wybudzanie.', true, 'Fundacja "A kogo"');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (7, 'Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji życiowej.', false, 'Fundacja “Dla dzieci"');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (8, 'Cel i misja: Pomoc dzieciom z ubogich rodzin.', false, 'Fundacja “Bez domu”');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (9, 'Cel i misja: Pomoc dzieciom z ubogich rodzin.', false, 'Fundacja “Bez domu”');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (10, 'Pomagamy dzieciom z zespołem lenia. Pomagamy konkretnie.', true, 'Fundacja "Dlaczego nie spóbować"');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (11, 'Pomoc w najczystszej postaci.', true, 'Nazwa fundacji POMOC');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (12, 'Opis całkiem nowej fundacji', false, 'Nowa fundacja');
INSERT INTO `charity-donation`.institution (id, description, enabled, name) VALUES (13, 'Fundacja założona dosłownie minutę temu', false, 'Moja najnowsza fundacja');